services:
  mongodb:
    image: mongo:7
    container_name: delivery-food-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: DeliveryFood

volumes:
  mongo_data:
